version: '3.9'
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - KEYCLOAK_URL
      - KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CLIENT_SECRET
    depends_on:
      - keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"

  shiny:
    build:
      context: ./shiny
    ports:
      - "${SHINY_PORT:-3838}:3838" # Valeur par défaut si SHINY_PORT n'est pas défini
    depends_on:
      - api
    env_file: .env
    environment:
      - KEYCLOAK_URL
      - KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CLIENT_SECRET
    volumes:
      - ./shiny/config:/srv/shiny-server/config # Ajusté pour éviter les conflits potentiels
